[project]
name = "uirs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "arinastyran", email = "arina.styran@mail.ru" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "plotly>=7.0.0",
    "scikit-learn>=1.9.1",
]

[project.scripts]
uirs = "uirs:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
